//go:build loadtest

package loadtest

import (
	"context"
	"errors"
	"fmt"
	"math/rand/v2"
	"sort"
	"strconv"
	"strings"
	"time"

	flywheel "github.com/mrz1836/go-flywheel"
	"gorm.io/datatypes"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// ErrClaimSQLUnrecognized reports that the statement the PostgreSQL driver
// emitted does not carry the class predicate this file knows how to rewrite.
//
// It is a hard error rather than a skipped cell on purpose. The whole point of
// capturing the driver's own SQL is that the published plans describe the query
// the runtime actually runs; if the driver's spelling changes underneath, the
// alternative to failing here is silently explaining P0 twice and labelling one
// of them P1.
var ErrClaimSQLUnrecognized = errors.New("captured claim SQL does not carry the expected class predicate")

// claimIndexName is the index the claim is supposed to use. Every variant is
// installed under this one name so the plan output is directly comparable across
// them — a plan that names a different index would not be.
const claimIndexName = "jobs_ready"

// claimStatePredicate is the partial-index predicate the shipped jobs_ready
// carries. The hand-written variants below splice it rather than restating the
// state list, and TestExplainVariantsSharePartialPredicate asserts the shipped
// DDL still contains it — so a change to the runtime's claimable states cannot
// leave the candidate indexes describing a different set of rows than the
// control does.
const claimStatePredicate = `WHERE state IN ('available', 'retryable', 'scheduled')`

// deletedPredicate narrows a candidate index to the rows the claim can actually
// take. The claim filters deleted_at IS NULL (driver_postgres.go) but the
// shipped index predicate does not, so every candidate tuple needs a heap visit
// to answer it.
const deletedPredicate = ` AND deleted_at IS NULL`

// Predicate spellings under test.
const (
	// predicateEmitted is the class clause exactly as the PostgreSQL driver
	// writes it today: an OR on the index's second column.
	predicateEmitted = "P0"
	// predicateInList is the spelling the SQLite driver already uses
	// (driver_sqlite.go). Whether PostgreSQL 17's btree ScalarArrayOp execution
	// preserves index ordering through it is the open question this matrix
	// exists to answer.
	predicateInList = "P1"
)

// explainSeedClasses is how many distinct executor_class values the seed spreads
// rows across: the routed class, the empty wildcard, and two foreign classes. A
// routed claim therefore matches half the table, which is what makes "the class
// filter's heap visits" a real cost rather than a rounding error — a seed in
// which every row matched would flatter any variant that drops the column from
// the key.
const explainSeedClasses = 4

// defaultExplainQueues and defaultExplainLimit are the matrix's shape defaults.
// The limit is the runner's per-poll batch at the published baseline's
// concurrency (Workers: 8), which is what makes "a Sort over more than LIMIT
// rows" the failure signature it is.
const (
	defaultExplainQueues = 3
	defaultExplainLimit  = 8
)

// ExplainConfig declares one characterization run: what to seed, and what shape
// of claim to explain against it.
//
// The zero value is not runnable — DSN and Jobs are required. Everything else
// defaults through validate.
type ExplainConfig struct {
	// DSN is the PostgreSQL target. Required. It never reaches the report: see
	// redactDSN.
	DSN string
	// Jobs is how many claimable rows to seed. Required, positive.
	Jobs int
	// Queues is how many distinct queues the rows are spread across. The
	// conditions then claim from one of them or from all of them, which is the
	// `queue IN (...)` cardinality the matrix varies.
	Queues int
	// Seed makes the seeded workload reproducible; it is the same seed the
	// scenario harness takes, and the rows are generated by the same generator.
	Seed int64
	// ExecutorClass is the class a routed claim asks for.
	ExecutorClass string
	// Limit is the claim's batch size — the runner's Concurrency.
	Limit int
	// Lease is the lease duration stamped by the claim. It changes nothing about
	// the plan; it exists so the captured statement is the one a configured
	// runner would emit.
	Lease time.Duration
}

// validate returns a normalized copy of cfg, or an error naming the field at
// fault. It copies rather than mutating for the same reason Config.validate
// does: a caller's config is never silently rewritten.
func (cfg ExplainConfig) validate() (ExplainConfig, error) {
	if cfg.DSN == "" {
		return ExplainConfig{}, fmt.Errorf("loadtest: %w", ErrNoDSN)
	}
	if cfg.Jobs <= 0 {
		return ExplainConfig{}, fmt.Errorf("loadtest: Jobs must be positive, got %d: %w", cfg.Jobs, ErrInvalidConfig)
	}
	if cfg.Queues < 0 {
		return ExplainConfig{}, fmt.Errorf("loadtest: Queues must not be negative, got %d: %w", cfg.Queues, ErrInvalidConfig)
	}
	if cfg.Queues == 0 {
		cfg.Queues = defaultExplainQueues
	}
	if cfg.Limit < 0 {
		return ExplainConfig{}, fmt.Errorf("loadtest: Limit must not be negative, got %d: %w", cfg.Limit, ErrInvalidConfig)
	}
	if cfg.Limit == 0 {
		cfg.Limit = defaultExplainLimit
	}
	if cfg.Lease <= 0 {
		cfg.Lease = time.Minute
	}
	if cfg.ExecutorClass == "" {
		cfg.ExecutorClass = defaultExecutorClass
	}
	return cfg, nil
}

// explainCondition is one runtime claim shape: which queues it names and whether
// it routes by class. The set of them is the matrix's rows.
type explainCondition struct {
	// Name is the condition label carried into the report.
	Name string
	// Queues is how many of the seeded queues the claim names.
	Queues int
	// ClaimAny mirrors the runner's ClaimAnyClass: it drops the class predicate
	// entirely, which is the second of the two ways the claim misses jobs_ready.
	ClaimAny bool
	// Idle names a queue with no ready rows instead of a seeded one.
	Idle bool
	// Desc is the human-readable shape, for the report header.
	Desc string
}

// idleQueue is a queue name the seed never writes to.
//
// It is how the matrix measures an empty poll, which is not an edge case: a
// runner polls every few milliseconds whether or not there is work, so on any
// quiet queue the overwhelming majority of claims a deployment ever issues
// return nothing. An index that answers a hit quickly and a miss slowly would be
// a worse deployment than the one it replaced.
const idleQueue = "q-idle"

// explainConditions returns the matrix's claim shapes.
//
// A through D are the four shapes the plan of record names: the two queue
// cardinalities crossed with the two routing modes. E and F are additions —
// the same two routing modes against a queue with nothing ready — because a
// candidate index can fix every one of A through D and still ruin the case a
// deployment spends most of its wall clock in.
func explainConditions() []explainCondition {
	return []explainCondition{
		{Name: "A", Queues: 1, ClaimAny: false, Desc: "1 queue,  routed by executor_class"},
		{Name: "B", Queues: 3, ClaimAny: false, Desc: "3 queues, routed by executor_class"},
		{Name: "C", Queues: 1, ClaimAny: true, Desc: "1 queue,  ClaimAnyClass (no class predicate)"},
		{Name: "D", Queues: 3, ClaimAny: true, Desc: "3 queues, ClaimAnyClass (no class predicate)"},
		{Name: "E", Queues: 1, ClaimAny: false, Idle: true, Desc: "idle queue, routed — the empty poll"},
		{Name: "F", Queues: 1, ClaimAny: true, Idle: true, Desc: "idle queue, ClaimAnyClass — the empty poll"},
	}
}

// explainVariant is one jobs_ready definition under test.
type explainVariant struct {
	// Name is the variant label carried into the report.
	Name string
	// Desc says what the definition is and why it is a candidate.
	Desc string
	// DDL creates the index. An empty DDL means the variant is "index absent",
	// which reproduces the published baseline's index-absent row.
	DDL string
	// Only, when non-empty, restricts the variant to that one condition. It
	// exists for the INCLUDE variant, which is a question about one shape rather
	// than a candidate for the whole matrix.
	Only string
}

// variantIndexDDL renders a candidate jobs_ready definition.
//
// Every candidate carries the shipped partial predicate plus deleted_at IS NULL,
// so the only thing that varies between them is the key — which is what makes a
// delta between two variants attributable to the column order rather than to the
// rows the index covers.
func variantIndexDDL(columns, include string) string {
	ddl := "CREATE INDEX IF NOT EXISTS " + claimIndexName + " ON jobs (" + columns + ")"
	if include != "" {
		ddl += " INCLUDE (" + include + ")"
	}
	return ddl + " " + claimStatePredicate + deletedPredicate
}

// explainVariants returns the index definitions under test, control first.
//
// V0 is pulled from the runtime's own IndexSet rather than re-typed. That is the
// same rule the scenario harness follows for its index conditions, and for the
// same reason: a control the harness spells itself is a control that drifts from
// the runtime silently, and then the published plans describe an index nobody
// ships.
func explainVariants() ([]explainVariant, error) {
	shipped, err := shippedClaimIndexDDL()
	if err != nil {
		return nil, err
	}
	return []explainVariant{
		{
			Name: "V-", Desc: "absent — reproduces the baseline's index-absent row",
			DDL: "",
		},
		{
			Name: "V0", Desc: "as shipped, from flywheel.IndexSet(\"postgres\")",
			DDL: shipped,
		},
		{
			Name: "V1", Desc: "V0 + deleted_at IS NULL in the predicate",
			// Derived from the shipped DDL by appending the predicate, so V1 is
			// provably V0 plus one clause rather than a retyped approximation of it.
			DDL: shipped + deletedPredicate,
		},
		{
			Name: "V2", Desc: "ordering columns first: (priority, scheduled_at, queue, executor_class)",
			DDL: variantIndexDDL("priority, scheduled_at, queue, executor_class", ""),
		},
		{
			Name: "V3", Desc: "class dropped from the key: (queue, priority, scheduled_at)",
			DDL: variantIndexDDL("queue, priority, scheduled_at", ""),
		},
		{
			Name: "V4", Desc: "V1 + INCLUDE (id), measured under condition A only",
			DDL:  variantIndexDDL("queue, executor_class, priority, scheduled_at", "id"),
			Only: "A",
		},
	}, nil
}

// shippedClaimIndexDDL finds the claim index in the runtime's own index set.
func shippedClaimIndexDDL() (string, error) {
	set, err := flywheel.IndexSet("postgres")
	if err != nil {
		return "", fmt.Errorf("loadtest: index set: %w", err)
	}
	for _, idx := range set {
		if idx.Name == claimIndexName {
			return idx.DDL, nil
		}
	}
	return "", fmt.Errorf("loadtest: %w: the runtime's index set has no %s", ErrInvalidConfig, claimIndexName)
}

// PlanSummary is the handful of numbers a reader compares cells by, lifted out
// of the plan text.
//
// The full plan is kept alongside it — this is a reading aid, not a replacement.
// A summary that disagreed with the text it summarizes would be worse than no
// summary at all, so every field here is parsed from the text rather than
// inferred from the query.
type PlanSummary struct {
	// Scan is the scan node the claim's inner select drives, verbatim.
	Scan string `json:"scan"`
	// ScanKind is that node's type: "Seq Scan", "Index Scan", "Bitmap Heap
	// Scan", and so on.
	ScanKind string `json:"scan_kind"`
	// IndexUsed names the index, when the scan is an index scan.
	IndexUsed string `json:"index_used,omitempty"`
	// ScanRows is how many rows the scan actually returned. Against a LIMIT of
	// 8, a scan returning six figures is the whole finding.
	ScanRows int64 `json:"scan_rows"`
	// Sorted reports whether a Sort node sits above the scan. A Sort over more
	// than LIMIT rows is the failure signature.
	Sorted bool `json:"sorted"`
	// SortMethod is the Sort node's method line, which is where an external
	// merge and its spill size appear.
	SortMethod string `json:"sort_method,omitempty"`
	// RowsRemoved is how many rows the scan's filter discarded — the cost of
	// applying a predicate at the heap instead of in the index.
	RowsRemoved int64 `json:"rows_removed_by_filter"`
	// SharedHit and SharedRead are the statement's buffer totals.
	SharedHit  int64 `json:"shared_hit"`
	SharedRead int64 `json:"shared_read"`
	// PlanningMS and ExecutionMS are the reported times.
	PlanningMS  float64 `json:"planning_ms"`
	ExecutionMS float64 `json:"execution_ms"`
}

// ExplainCell is one measured square of the matrix.
type ExplainCell struct {
	Condition string      `json:"condition"`
	Predicate string      `json:"predicate"`
	Variant   string      `json:"variant"`
	Summary   PlanSummary `json:"summary"`
	Plan      []string    `json:"plan"`
}

// Key is the cell's stable label, "A/P0/V1".
func (c ExplainCell) Key() string { return c.Condition + "/" + c.Predicate + "/" + c.Variant }

// ExplainStatement is one captured claim, kept once rather than per cell: every
// variant explains the same bytes, so repeating the statement in every cell
// would triple the artifact for no information.
type ExplainStatement struct {
	Condition string `json:"condition"`
	Predicate string `json:"predicate"`
	SQL       string `json:"sql"`
}

// ExplainReport is one characterization run.
type ExplainReport struct {
	// Target is the redacted DSN — host, port, database, and nothing else.
	Target string `json:"target"`
	// Server is the target's version string.
	Server string `json:"server"`
	// Schema is the isolated schema the run provisioned and dropped.
	Schema string `json:"schema"`
	// Jobs, Queues, Classes, Limit, and Seed describe the seeded table.
	Jobs    int      `json:"jobs"`
	Queues  []string `json:"queues"`
	Classes []string `json:"executor_classes"`
	Limit   int      `json:"claim_limit"`
	Seed    int64    `json:"seed"`
	// TableBytes and IndexBytes are the seeded table's size at measurement time.
	TableBytes int64 `json:"table_bytes"`

	Conditions []explainCondition `json:"-"`
	Variants   []explainVariant   `json:"-"`
	Statements []ExplainStatement `json:"statements"`
	Cells      []ExplainCell      `json:"cells"`
	Notes      []string           `json:"notes,omitempty"`
}

// claimSQLRecorder is a gorm logger that keeps the last statement it traced.
//
// GORM hands Trace a closure returning the final SQL with bind values already
// interpolated by Dialector.Explain, which is directly re-executable — so this
// is how the tool explains the query the driver actually emits without the
// driver growing a seam to expose it. The claim SQL lives once, inside an
// unexported method; re-typing it here would be the same class of mistake as a
// hand-copied index list.
type claimSQLRecorder struct {
	sql string
}

// LogMode is part of logger.Interface. The recorder has one mode.
func (r *claimSQLRecorder) LogMode(logger.LogLevel) logger.Interface { return r }

// Info, Warn, and Error are discarded: this logger exists to capture SQL, and a
// harness that printed GORM's chatter would bury the artifact it is writing.
func (r *claimSQLRecorder) Info(context.Context, string, ...any)  {}
func (r *claimSQLRecorder) Warn(context.Context, string, ...any)  {}
func (r *claimSQLRecorder) Error(context.Context, string, ...any) {}

// Trace records the statement. It keeps the last one rather than accumulating:
// each capture drives exactly one Dequeue, and reading the field straight after
// is what makes the pairing unambiguous.
func (r *claimSQLRecorder) Trace(_ context.Context, _ time.Time, fc func() (string, int64), _ error) {
	sql, _ := fc()
	r.sql = sql
}

// captureClaimSQL runs one Dequeue through the real PostgreSQL driver and
// returns the statement it emitted.
//
// The call runs inside a transaction that is always rolled back. That is not
// tidiness: Dequeue is an UPDATE, and a capture that committed would claim rows
// out of the table the matrix is about to measure against.
func captureClaimSQL(
	ctx context.Context, db *gorm.DB, queues []string, class string, claimAny bool, limit int, lease time.Duration,
) (string, error) {
	rec := &claimSQLRecorder{}

	// The pool passed here is the capture pool, opened for this purpose alone, so
	// swapping its logger cannot affect anything else the run does.
	prev := db.Logger
	db.Logger = rec
	defer func() { db.Logger = prev }()

	tx := db.WithContext(ctx).Begin()
	if tx.Error != nil {
		return "", fmt.Errorf("loadtest: begin capture transaction: %w", tx.Error)
	}
	_, dequeueErr := flywheel.NewPostgresDriver(tx).Dequeue(
		ctx, queues, flywheel.ExecutorClass(class), claimAny, limit, lease,
	)
	if err := tx.Rollback().Error; err != nil {
		return "", fmt.Errorf("loadtest: roll back capture transaction: %w", err)
	}
	if dequeueErr != nil {
		return "", fmt.Errorf("loadtest: capture claim SQL: %w", dequeueErr)
	}
	if strings.TrimSpace(rec.sql) == "" {
		return "", fmt.Errorf("loadtest: %w: the driver traced no statement", ErrClaimSQLUnrecognized)
	}
	return pinLeaseToken(rec.sql), nil
}

// pinnedLeaseToken is the value every captured statement's lease_token is
// rewritten to.
//
// It is a syntactically valid UUIDv7 with a fixed body, so the statement stays
// exactly as executable as the one the driver produced.
const pinnedLeaseToken = "00000000-0000-7000-8000-000000000000"

// pinLeaseToken replaces the claim's freshly minted lease token with a fixed
// one.
//
// The token is a random UUID the driver mints per call. It is assigned in the
// UPDATE's SET list and appears in no predicate, so it cannot reach the planner
// and pinning it changes no plan. What pinning buys is two things the artifact
// needs: a matrix re-run produces a statement that diffs cleanly against the
// previous one instead of differing by a random value in every cell, and a
// committed file stops carrying a fresh high-entropy string that every secret
// scanner in every consumer repository will flag.
//
// A statement without the marker is returned unchanged rather than treated as an
// error: the marker is a convenience, and the fidelity check that matters is
// rewriteClassPredicate's.
func pinLeaseToken(sql string) string {
	const marker = "lease_token = '"
	start := strings.Index(sql, marker)
	if start < 0 {
		return sql
	}
	valueAt := start + len(marker)
	end := strings.Index(sql[valueAt:], "'")
	if end < 0 {
		return sql
	}
	return sql[:valueAt] + pinnedLeaseToken + sql[valueAt+end:]
}

// orClassPredicate and inClassPredicate are the two spellings of the class
// clause. They are written as functions of the class literal so the rewrite
// below can assert the emitted form is present before replacing it.
func orClassPredicate(class string) string {
	return "(executor_class = " + pgLiteral(class) + " OR executor_class = '')"
}

func inClassPredicate(class string) string {
	return "executor_class IN (" + pgLiteral(class) + ", '')"
}

// pgLiteral renders a string as a PostgreSQL literal, matching how the GORM
// dialector interpolates one.
func pgLiteral(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }

// rewriteClassPredicate turns the emitted OR spelling into the IN spelling.
//
// It is one documented Replace of one clause, so everything except the thing
// under test stays byte-identical between P0 and P1 — the reason the two plans
// are comparable at all. A statement that does not contain the emitted spelling
// is an error, not a pass-through: see ErrClaimSQLUnrecognized.
func rewriteClassPredicate(sql, class string) (string, error) {
	from := orClassPredicate(class)
	if !strings.Contains(sql, from) {
		return "", fmt.Errorf("loadtest: %w: expected %s", ErrClaimSQLUnrecognized, from)
	}
	return strings.Replace(sql, from, inClassPredicate(class), 1), nil
}

// installClaimIndex drops whatever jobs_ready the schema carries and creates the
// variant's definition in its place.
//
// The unconditional drop is the point. Every variant ships as
// CREATE INDEX IF NOT EXISTS jobs_ready, which on a schema that already has an
// index of that name does nothing and returns success — so without the drop,
// every variant after the first would silently measure the first one's
// definition.
func installClaimIndex(ctx context.Context, db *gorm.DB, ddl string) error {
	if err := db.WithContext(ctx).Exec(`DROP INDEX IF EXISTS ` + claimIndexName).Error; err != nil {
		return fmt.Errorf("loadtest: drop %s: %w", claimIndexName, err)
	}
	if ddl == "" {
		return nil
	}
	if err := db.WithContext(ctx).Exec(ddl).Error; err != nil {
		return fmt.Errorf("loadtest: create %s: %w", claimIndexName, err)
	}
	// A fresh index carries no planner statistics until the table is analyzed,
	// and a variant measured against stale statistics is a variant measured
	// against the previous variant's plan.
	if err := db.WithContext(ctx).Exec(`ANALYZE jobs`).Error; err != nil {
		return fmt.Errorf("loadtest: analyze jobs: %w", err)
	}
	return nil
}

// explainStatement captures EXPLAIN (ANALYZE, BUFFERS) for one statement.
//
// ANALYZE executes what it explains, and what it explains here is the claim —
// an UPDATE that would leave the seeded table permanently smaller and every
// later cell measuring a different table. So the whole thing runs inside a
// transaction, and a rollback that fails is a hard error rather than a warning:
// the isolation this function promises is the only reason the matrix's cells are
// comparable.
func explainStatement(ctx context.Context, db *gorm.DB, sql string) ([]string, error) {
	tx := db.WithContext(ctx).Begin()
	if tx.Error != nil {
		return nil, fmt.Errorf("loadtest: begin explain transaction: %w", tx.Error)
	}
	var lines []string
	explainErr := tx.Raw("EXPLAIN (ANALYZE, BUFFERS) " + sql).Scan(&lines).Error
	if err := tx.Rollback().Error; err != nil {
		return nil, fmt.Errorf("loadtest: roll back explain transaction: %w", errors.Join(explainErr, err))
	}
	if explainErr != nil {
		return nil, fmt.Errorf("loadtest: explain claim: %w", explainErr)
	}
	return lines, nil
}

// scanKinds are the node types that read a table, longest first so a prefix
// match cannot classify a "Bitmap Heap Scan" as a "Heap Scan".
//
//nolint:gochecknoglobals // a fixed vocabulary, not state
var scanKinds = []string{
	"Parallel Bitmap Heap Scan", "Parallel Index Only Scan", "Parallel Index Scan", "Parallel Seq Scan",
	"Bitmap Heap Scan", "Bitmap Index Scan", "Index Only Scan", "Index Scan", "Seq Scan", "Tid Scan",
}

// parsePlan lifts the comparison numbers out of a text plan.
//
// It reads only the CTE subtree. The claim's outer UPDATE joins the CTE back to
// jobs on the primary key, so the whole statement always contains a second index
// scan that has nothing to do with the question — a parser that took the first
// scan it saw would report jobs_pkey and call the claim fixed.
func parsePlan(lines []string) PlanSummary {
	var s PlanSummary
	s.PlanningMS = -1
	s.ExecutionMS = -1

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, "Planning Time:"):
			s.PlanningMS = parseMillis(trimmed)
		case strings.HasPrefix(trimmed, "Execution Time:"):
			s.ExecutionMS = parseMillis(trimmed)
		case strings.HasPrefix(trimmed, "Buffers:") && s.SharedHit == 0 && s.SharedRead == 0:
			// The first Buffers line belongs to the root node and is cumulative
			// over the whole statement, which is the total a reader wants.
			s.SharedHit, s.SharedRead = parseBuffers(trimmed)
		}
	}

	for _, line := range claimSubtree(lines) {
		trimmed := strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(line), "->"))
		switch {
		case s.Scan == "" && scanKindOf(trimmed) != "":
			// The node label only. The cost and actual segments are already in the
			// summary's own fields and in the plan text below it, and repeating
			// them here would make the summary table unreadable.
			s.Scan = nodeLabel(trimmed)
			s.ScanKind = scanKindOf(trimmed)
			s.ScanRows = parseActualRows(trimmed)
			s.IndexUsed = parseIndexName(trimmed)
		case strings.HasPrefix(trimmed, "Sort Method:"):
			s.SortMethod = strings.TrimSpace(strings.TrimPrefix(trimmed, "Sort Method:"))
		case isSortNode(trimmed):
			s.Sorted = true
		case strings.HasPrefix(trimmed, "Rows Removed by Filter:"):
			s.RowsRemoved += parseTrailingInt(trimmed)
		}
	}
	return s
}

// claimSubtree returns the lines under the plan's CTE node.
//
// EXPLAIN's text format encodes the tree as indentation, so the subtree is every
// following line indented further than the CTE line itself. A statement without
// a CTE — which the claim always has, but a rewritten candidate might not —
// yields the whole plan rather than nothing, so a parser change cannot silently
// empty the summary.
func claimSubtree(lines []string) []string {
	start, depth := -1, 0
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "CTE ") {
			start, depth = i+1, indentOf(line)
			break
		}
	}
	if start < 0 {
		return lines
	}
	for i := start; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) != "" && indentOf(lines[i]) <= depth {
			return lines[start:i]
		}
	}
	return lines[start:]
}

// indentOf counts a plan line's leading spaces, which is its depth in the tree.
func indentOf(line string) int {
	for i := range len(line) {
		if line[i] != ' ' {
			return i
		}
	}
	return len(line)
}

// scanKindOf reports which scan node a plan line describes, or "" for a line
// that is not a scan.
func scanKindOf(line string) string {
	for _, kind := range scanKinds {
		if strings.HasPrefix(line, kind+" ") {
			return kind
		}
	}
	return ""
}

// isSortNode reports whether a plan line is a Sort node rather than one of the
// Sort node's own detail lines.
//
// The distinction is the whole reason this is a function: "Sort Key: ..." and
// "Sort Method: ..." both begin with "Sort", and a prefix match would classify
// them as sort nodes and swallow the method line the spill size lives on.
func isSortNode(line string) bool {
	label := nodeLabel(line)
	return label == "Sort" || label == "Incremental Sort"
}

// nodeLabel strips a plan node's cost and actual-time segments, leaving the node
// description.
func nodeLabel(line string) string {
	if i := strings.Index(line, "  (cost="); i >= 0 {
		return strings.TrimSpace(line[:i])
	}
	return strings.TrimSpace(line)
}

// parseIndexName pulls the index out of an "Index Scan using <name> on ..." line.
func parseIndexName(line string) string {
	const marker = " using "
	i := strings.Index(line, marker)
	if i < 0 {
		return ""
	}
	rest := line[i+len(marker):]
	name, _, _ := strings.Cut(rest, " ")
	return name
}

// parseActualRows reads the rows count out of a node's "(actual ... rows=N ...)"
// segment. The estimate's rows= is deliberately not read: an estimate that
// disagreed with reality is exactly what these plans exist to show.
func parseActualRows(line string) int64 {
	i := strings.Index(line, "(actual ")
	if i < 0 {
		return 0
	}
	return parseLabeledInt(line[i:], "rows=")
}

// parseBuffers reads shared hit and read counts off a Buffers line.
func parseBuffers(line string) (hit, read int64) {
	return parseLabeledInt(line, "shared hit="), parseLabeledInt(line, "read=")
}

// parseLabeledInt reads the integer that follows label, or zero if the label is
// absent or is not followed by digits.
func parseLabeledInt(s, label string) int64 {
	i := strings.Index(s, label)
	if i < 0 {
		return 0
	}
	rest := s[i+len(label):]
	end := 0
	for end < len(rest) && rest[end] >= '0' && rest[end] <= '9' {
		end++
	}
	n, err := strconv.ParseInt(rest[:end], 10, 64)
	if err != nil {
		return 0
	}
	return n
}

// parseTrailingInt reads the integer after a "Label: N" line's colon.
func parseTrailingInt(line string) int64 {
	_, after, found := strings.Cut(line, ":")
	if !found {
		return 0
	}
	n, err := strconv.ParseInt(strings.TrimSpace(after), 10, 64)
	if err != nil {
		return 0
	}
	return n
}

// parseMillis reads the number out of a "Planning Time: 0.095 ms" line.
func parseMillis(line string) float64 {
	_, after, found := strings.Cut(line, ":")
	if !found {
		return -1
	}
	value, _, _ := strings.Cut(strings.TrimSpace(after), " ")
	f, err := strconv.ParseFloat(value, 64)
	if err != nil {
		return -1
	}
	return f
}

// explainQueues names the queues the seed spreads rows across.
func explainQueues(n int) []string {
	queues := make([]string, n)
	for i := range queues {
		queues[i] = fmt.Sprintf("q%d", i)
	}
	return queues
}

// explainClasses names the executor classes the seed spreads rows across: the
// routed class, the empty wildcard, and two foreign ones. See explainSeedClasses
// for why the routed claim is deliberately left matching only half the table.
func explainClasses(class string) []string {
	return []string{class, "", class + "-b", class + "-c"}
}

// seedClaimable bulk-inserts the run's rows, all claimable, spread across the
// queues and classes.
//
// The rows come from the harness's own generator, so their priority spread and
// row width are the ones every other published artifact describes — a
// characterization run seeded with `{}` args would measure a table with a
// fraction of the pages a real one has, and understate every sequential scan in
// the matrix. Only the queue and class assignment is this function's own, since
// those are the two columns the matrix varies.
//
// Rows are materialized one batch at a time rather than all at once: at a
// million rows the difference is a few megabytes against a few hundred.
func seedClaimable(ctx context.Context, db *gorm.DB, cfg ExplainConfig, queues, classes []string) error {
	specs := generate(Config{Jobs: cfg.Jobs, Seed: cfg.Seed, Mix: WorkloadDrainOnly})
	ids := rand.New(rand.NewPCG(uint64(cfg.Seed), streamID)) //nolint:gosec // reproducibility, not security

	batch := make([]bulkJobRow, 0, bulkBatch)
	flush := func() error {
		if len(batch) == 0 {
			return nil
		}
		if err := db.WithContext(ctx).CreateInBatches(batch, bulkBatch).Error; err != nil {
			return fmt.Errorf("loadtest: seed claimable rows: %w", err)
		}
		batch = batch[:0]
		return nil
	}

	for i, spec := range specs {
		if err := ctx.Err(); err != nil {
			return fmt.Errorf("loadtest: seed interrupted after %d jobs: %w", i, err)
		}
		payload, err := marshalArgs(specToArgs(spec))
		if err != nil {
			return err
		}
		at := seedEpoch.Add(time.Duration(i) * time.Microsecond)
		batch = append(batch, bulkJobRow{
			ID:            newMonotoneID(at, ids),
			CreatedAt:     at,
			UpdatedAt:     at,
			Metadata:      datatypes.JSON(`{}`),
			Kind:          loadKind,
			Queue:         queues[i%len(queues)],
			Args:          datatypes.JSON(payload),
			Priority:      spec.Priority,
			State:         string(flywheel.StateAvailable),
			Attempt:       0,
			MaxAttempts:   25,
			ScheduledAt:   at,
			ExecutorClass: classes[i%len(classes)],
			Tags:          datatypes.JSON(`[]`),
		})
		if len(batch) == bulkBatch {
			if err := flush(); err != nil {
				return err
			}
		}
	}
	return flush()
}

// ExplainClaim characterizes the claim predicate against a freshly seeded table
// and returns the matrix.
//
// It provisions its own schema, installs the full production index set through
// the runtime's own IndexSet, seeds, walks the variant × condition × predicate
// matrix, and drops the schema. Nothing it measures survives it.
//
// The loop is variant-outer on purpose: building an index over a million rows
// costs seconds, and re-building it per cell would multiply the run's wall clock
// by the number of conditions for no additional information.
func ExplainClaim(ctx context.Context, cfg ExplainConfig) (ExplainReport, error) {
	cfg, err := cfg.validate()
	if err != nil {
		return ExplainReport{}, err
	}
	variants, err := explainVariants()
	if err != nil {
		return ExplainReport{}, err
	}

	queues := explainQueues(cfg.Queues)
	classes := explainClasses(cfg.ExecutorClass)
	report := ExplainReport{
		Target:     redactDSN(cfg.DSN),
		Jobs:       cfg.Jobs,
		Queues:     queues,
		Classes:    classes,
		Limit:      cfg.Limit,
		Seed:       cfg.Seed,
		Conditions: explainConditions(),
		Variants:   variants,
	}

	admin, err := openPool(cfg.DSN, 2)
	if err != nil {
		return report, fmt.Errorf("loadtest: open admin pool: %w", err)
	}
	defer closePool(admin)
	if admin.Name() != "postgres" {
		return report, fmt.Errorf("loadtest: target dialect is %q: %w", admin.Name(), ErrUnsupportedDialect)
	}

	schema := newSchemaName()
	report.Schema = schema
	if err = createSchema(ctx, admin, schema); err != nil {
		return report, err
	}
	// The schema is dropped even when the run fails: a matrix that aborted
	// halfway through still leaves a million rows behind otherwise, and the next
	// run would be measuring against a full disk.
	defer func() { _ = dropSchema(context.WithoutCancel(ctx), admin, schema) }()

	db, err := openPool(withSearchPath(cfg.DSN, schema), 2)
	if err != nil {
		return report, fmt.Errorf("loadtest: open work pool: %w", err)
	}
	defer closePool(db)

	if err = installSchema(ctx, db, IndexesFull, StorageDefault); err != nil {
		return report, err
	}
	if err = seedClaimable(ctx, db, cfg, queues, classes); err != nil {
		return report, err
	}
	if err = db.WithContext(ctx).Exec(`ANALYZE jobs`).Error; err != nil {
		return report, fmt.Errorf("loadtest: analyze jobs: %w", err)
	}
	report.Server = scalarString(ctx, db, `SELECT version()`)
	report.TableBytes = scalarInt(ctx, db, `SELECT pg_total_relation_size('jobs')`)

	// Every statement is captured once, up front, against the shipped schema, and
	// every variant then explains the same bytes. Capturing per variant would let
	// the embedded now() drift between cells and make two plans differ for a
	// reason the matrix is not about.
	statements, err := captureStatements(ctx, cfg, schema, queues)
	if err != nil {
		return report, err
	}
	report.Statements = statements

	for _, variant := range variants {
		if err = installClaimIndex(ctx, db, variant.DDL); err != nil {
			return report, err
		}
		for _, stmt := range statements {
			if variant.Only != "" && variant.Only != stmt.Condition {
				continue
			}
			lines, explainErr := explainStatement(ctx, db, stmt.SQL)
			if explainErr != nil {
				return report, explainErr
			}
			report.Cells = append(report.Cells, ExplainCell{
				Condition: stmt.Condition, Predicate: stmt.Predicate, Variant: variant.Name,
				Summary: parsePlan(lines), Plan: lines,
			})
		}
	}

	sortCells(report.Cells)
	report.Notes = explainNotes(cfg, classes)
	return report, nil
}

// captureStatements builds the (condition, predicate) statements the matrix
// explains, taking each one from the driver rather than from this file.
func captureStatements(
	ctx context.Context, cfg ExplainConfig, schema string, queues []string,
) ([]ExplainStatement, error) {
	// A pool of its own, so installing the recording logger cannot perturb the
	// pool the matrix measures on.
	capture, err := openPool(withSearchPath(cfg.DSN, schema), 1)
	if err != nil {
		return nil, fmt.Errorf("loadtest: open capture pool: %w", err)
	}
	defer closePool(capture)

	var out []ExplainStatement
	for _, cond := range explainConditions() {
		named := queues
		if cond.Queues < len(queues) {
			named = queues[:cond.Queues]
		}
		if cond.Idle {
			named = []string{idleQueue}
		}
		sql, captureErr := captureClaimSQL(ctx, capture, named, cfg.ExecutorClass, cond.ClaimAny, cfg.Limit, cfg.Lease)
		if captureErr != nil {
			return nil, captureErr
		}
		out = append(out, ExplainStatement{Condition: cond.Name, Predicate: predicateEmitted, SQL: sql})

		// The IN spelling only means something where a class predicate exists at
		// all: a ClaimAnyClass claim has no clause to respell.
		if cond.ClaimAny {
			continue
		}
		rewritten, rewriteErr := rewriteClassPredicate(sql, cfg.ExecutorClass)
		if rewriteErr != nil {
			return nil, rewriteErr
		}
		out = append(out, ExplainStatement{Condition: cond.Name, Predicate: predicateInList, SQL: rewritten})
	}
	return out, nil
}

// sortCells orders the matrix by condition, then predicate, then variant, so the
// artifact reads as a table rather than as the order the loop happened to visit.
func sortCells(cells []ExplainCell) {
	sort.SliceStable(cells, func(i, j int) bool {
		if cells[i].Condition != cells[j].Condition {
			return cells[i].Condition < cells[j].Condition
		}
		if cells[i].Predicate != cells[j].Predicate {
			return cells[i].Predicate < cells[j].Predicate
		}
		return cells[i].Variant < cells[j].Variant
	})
}

// explainNotes records the caveats a reader needs to interpret the matrix. They
// print with the numbers, not in a file somewhere else.
func explainNotes(cfg ExplainConfig, classes []string) []string {
	return []string{
		fmt.Sprintf(
			"Rows are spread evenly across %d executor classes (%s), so a routed claim matches half the table. "+
				"A seed in which every row matched would flatter any variant that drops the class from the key.",
			len(classes), strings.Join(quoteEmpty(classes), ", "),
		),
		fmt.Sprintf(
			"Every row is claimable: state='available', deleted_at IS NULL, scheduled_at in the past. "+
				"The claim's LIMIT is %d, so any Sort over more than %d rows is work the plan did not need to do.",
			cfg.Limit, cfg.Limit,
		),
		fmt.Sprintf(
			"Conditions E and F name %q, which the seed never writes to, so they measure an empty poll. "+
				"That is the case a deployment spends most of its wall clock in — a runner polls on a fixed "+
				"interval whether or not there is work — and an index that answers a hit quickly and a miss "+
				"slowly would be worse than the one it replaced.",
			idleQueue,
		),
		"Every statement was captured from postgresDriver.Dequeue through a recording GORM logger and " +
			"explained verbatim; P1 differs from P0 by exactly one documented Replace of the class clause.",
		"EXPLAIN (ANALYZE) executes the claim, so every capture ran inside a transaction that was rolled back. " +
			"The seeded table is identical for every cell.",
	}
}

// quoteEmpty renders a class list for prose, naming the empty wildcard rather
// than printing nothing for it.
func quoteEmpty(classes []string) []string {
	out := make([]string, len(classes))
	for i, c := range classes {
		out[i] = c
		if c == "" {
			out[i] = "(empty wildcard)"
		}
	}
	return out
}

// closePool releases a pool's underlying connections. Errors are dropped: this
// runs on deferred teardown paths where the measurement is already taken, and
// failing a completed run because a socket close returned late would throw away
// the artifact.
func closePool(db *gorm.DB) {
	if db == nil {
		return
	}
	if sqlDB, err := db.DB(); err == nil {
		_ = sqlDB.Close()
	}
}

// scalarString and scalarInt read one value for the report header. A failure
// yields the zero value: these are descriptive fields, and a run that measured
// its whole matrix should not fail because the server declined to state its
// version.
func scalarString(ctx context.Context, db *gorm.DB, query string) string {
	var out string
	if err := db.WithContext(ctx).Raw(query).Scan(&out).Error; err != nil {
		return ""
	}
	return out
}

func scalarInt(ctx context.Context, db *gorm.DB, query string) int64 {
	var out int64
	if err := db.WithContext(ctx).Raw(query).Scan(&out).Error; err != nil {
		return 0
	}
	return out
}
